export interface CatalogCategory {
  id: string
  title: string
  icon: string
  subtitle: string
  displayOrder: number
}

export interface CatalogGroup {
  id: string
  categoryId: string
  title: string
  icon: string
  displayOrder: number
  directServiceId?: string
}

export interface CatalogItem {
  id: string
  categoryId: string
  groupId: string
  title: string
  displayOrder: number
  handoffRequired: boolean
  handoffMode: string
}

// Generated from the approved Phase 2 Master Catalog.
// Included rows: active=true, review_status=APPROVED, lifecycle_status=ACTIVE.
// Source workbook remains the governance source of truth.

export const catalogCategories: CatalogCategory[] = [
  {
    id: "company-formation",
    title: "تأسيس شركات",
    icon: "🏢",
    subtitle: "ابدأ شركتك بخطوات واضحة ومنظمة",
    displayOrder: 1,
  },
  {
    id: "entrepreneurial-licenses",
    title: "إصدار التراخيص الريادية",
    icon: "🚀",
    subtitle: "احتضان الأفكار الريادية والمبتكرة وإصدار التراخيص",
    displayOrder: 2,
  },
  {
    id: "government-procedures",
    title: "الإجراءات الحكومية وإدارة المنصات",
    icon: "🧭",
    subtitle: "إدارة المنصات الحكومية وإنجاز إجراءات الشركات والمؤسسات، بما فيها الزيارات اللازمة.",
    displayOrder: 4,
  },
  {
    id: "legal-services",
    title: "الخدمات القانونية",
    icon: "⚖️",
    subtitle: "محامون موثوقون في القضايا التجارية وجميع الخدمات القانونية",
    displayOrder: 5,
  },
  {
    id: "financial-services",
    title: "الخدمات المالية",
    icon: "📊",
    subtitle: "مستشارون ماليون ومحاسبون قانونيون معتمدون في خدمة شركتك",
    displayOrder: 6,
  },
  {
    id: "marketing-feasibility",
    title: "خدمات التسويق ودراسة الجدوى",
    icon: "📈",
    subtitle: "خبراء يساعدونك في تقييم جدوى مشروعك وتسويقه وتطوير فرص نموه.",
    displayOrder: 7,
  },
  {
    id: "premium-residency",
    title: "الإقامة المميزة والإقامة الذهبية",
    icon: "⭐",
    subtitle: "إصدار الإقامة المميزة والذهبية والاستثمارية",
    displayOrder: 8,
  },
  {
    id: "ready-workspaces",
    title: "استئجار مساحة عمل جاهزة",
    icon: "🪑",
    subtitle: "مساحات عمل مجهزة ومرنة تناسب احتياجات الأفراد والشركات.",
    displayOrder: 9,
  },
]

export const catalogGroups: CatalogGroup[] = [
  {
    id: "commercial-company",
    categoryId: "company-formation",
    title: "تأسيس شركة تجارية",
    icon: "🏢",
    displayOrder: 1,
  },
  {
    id: "service-company",
    categoryId: "company-formation",
    title: "تأسيس شركة خدمية أو عقارية",
    icon: "🧩",
    displayOrder: 2,
  },
  {
    id: "industrial-company",
    categoryId: "company-formation",
    title: "تأسيس شركة صناعية",
    icon: "🏭",
    displayOrder: 3,
  },
  {
    id: "joint-stock-company",
    categoryId: "company-formation",
    title: "تأسيس شركة مساهمة",
    icon: "📑",
    displayOrder: 4,
    directServiceId: "EST-CF-JSC-001",
  },
  {
    id: "entrepreneurial-company",
    categoryId: "entrepreneurial-licenses",
    title: "تأسيس شركة ريادية",
    icon: "🚀",
    displayOrder: 1,
    directServiceId: "EST-CF-ENTR-001",
  },
  {
    id: "entrepreneurial-incubation",
    categoryId: "entrepreneurial-licenses",
    title: "احتضان مشروع ريادي",
    icon: "💡",
    displayOrder: 2,
    directServiceId: "EST-ENT-INC-001",
  },
  {
    id: "other-company-types",
    categoryId: "company-formation",
    title: "أنواع أخرى",
    icon: "📁",
    displayOrder: 5,
  },
  {
    id: "government-platform-management",
    categoryId: "government-procedures",
    title: "إدارة المنصات الحكومية",
    icon: "🖥️",
    displayOrder: 1,
    directServiceId: "EST-GOV-MGMT-001",
  },
  {
    id: "government-entity-visit",
    categoryId: "government-procedures",
    title: "إنجاز إجراء بزيارة جهة حكومية",
    icon: "📍",
    displayOrder: 2,
    directServiceId: "EST-GOV-VISIT-001",
  },
  {
    id: "commercial-cases",
    categoryId: "legal-services",
    title: "القضايا التجارية",
    icon: "⚖️",
    displayOrder: 1,
    directServiceId: "EST-LEGAL-COMM-001",
  },
  {
    id: "administrative-cases",
    categoryId: "legal-services",
    title: "القضايا الإدارية",
    icon: "🏛️",
    displayOrder: 2,
    directServiceId: "EST-LEGAL-ADMIN-001",
  },
  {
    id: "labor-cases",
    categoryId: "legal-services",
    title: "القضايا العمالية",
    icon: "👥",
    displayOrder: 3,
    directServiceId: "EST-LEGAL-LABOR-001",
  },
  {
    id: "arbitration-dispute-resolution",
    categoryId: "legal-services",
    title: "التحكيم وتسوية المنازعات",
    icon: "🤝",
    displayOrder: 4,
    directServiceId: "EST-LEGAL-ARB-001",
  },
  {
    id: "contracts-agreements",
    categoryId: "legal-services",
    title: "صياغة العقود والاتفاقيات",
    icon: "📝",
    displayOrder: 5,
    directServiceId: "EST-LEGAL-CONTRACT-001",
  },
  {
    id: "other-legal-cases",
    categoryId: "legal-services",
    title: "قضايا أخرى",
    icon: "📁",
    displayOrder: 6,
    directServiceId: "EST-LEGAL-OTHER-001",
  },
  {
    id: "financial-consultant",
    categoryId: "financial-services",
    title: "مستشار مالي",
    icon: "📊",
    displayOrder: 1,
    directServiceId: "EST-FIN-CONS-001",
  },
  {
    id: "chartered-accountant",
    categoryId: "financial-services",
    title: "محاسب قانوني",
    icon: "🧾",
    displayOrder: 2,
    directServiceId: "EST-FIN-CPA-001",
  },
  {
    id: "data-entry-account-review",
    categoryId: "financial-services",
    title: "مدخلو بيانات ومراجعو حسابات",
    icon: "📋",
    displayOrder: 3,
    directServiceId: "EST-FIN-DATA-001",
  },
  {
    id: "other-financial-services",
    categoryId: "financial-services",
    title: "مالية أخرى",
    icon: "📁",
    displayOrder: 4,
    directServiceId: "EST-FIN-OTHER-001",
  },
  {
    id: "feasibility-study",
    categoryId: "marketing-feasibility",
    title: "دراسة جدوى",
    icon: "📑",
    displayOrder: 1,
    directServiceId: "EST-MKT-FEAS-001",
  },
  {
    id: "marketing-business-development",
    categoryId: "marketing-feasibility",
    title: "التسويق وتطوير الأعمال",
    icon: "📈",
    displayOrder: 2,
    directServiceId: "EST-MKT-BIZDEV-001",
  },
  {
    id: "premium-business-investor",
    categoryId: "premium-residency",
    title: "إقامة مميزة لمستثمر أعمال",
    icon: "💼",
    displayOrder: 1,
    directServiceId: "EST-PR-GENERAL-005",
  },
  {
    id: "premium-property-owner",
    categoryId: "premium-residency",
    title: "إقامة مميزة لمالك عقار",
    icon: "🏠",
    displayOrder: 2,
    directServiceId: "EST-PR-GENERAL-003",
  },
  {
    id: "premium-entrepreneur",
    categoryId: "premium-residency",
    title: "إقامة مميزة لرائد أعمال",
    icon: "🚀",
    displayOrder: 3,
    directServiceId: "EST-PR-GENERAL-004",
  },
  {
    id: "premium-talent",
    categoryId: "premium-residency",
    title: "إقامة مميزة للموهبة",
    icon: "🌟",
    displayOrder: 4,
    directServiceId: "EST-PR-GENERAL-002",
  },
  {
    id: "premium-exceptional-competency",
    categoryId: "premium-residency",
    title: "إقامة مميزة للكفاءة الاستثنائية",
    icon: "🏅",
    displayOrder: 5,
    directServiceId: "EST-PR-GENERAL-001",
  },
  {
    id: "premium-fixed-term",
    categoryId: "premium-residency",
    title: "إقامة مميزة محددة المدة",
    icon: "🗓️",
    displayOrder: 6,
    directServiceId: "EST-PR-GENERAL-006",
  },
  {
    id: "premium-unlimited-term",
    categoryId: "premium-residency",
    title: "إقامة مميزة غير محددة المدة",
    icon: "♾️",
    displayOrder: 7,
    directServiceId: "EST-PR-GENERAL-007",
  },
  {
    id: "private-office",
    categoryId: "ready-workspaces",
    title: "مكتب مغلق",
    icon: "🚪",
    displayOrder: 1,
    directServiceId: "EST-WORK-PRIVATE-001",
  },
  {
    id: "shared-office",
    categoryId: "ready-workspaces",
    title: "مكتب مشترك",
    icon: "👥",
    displayOrder: 2,
    directServiceId: "EST-WORK-SHARED-001",
  },
]

export const catalogServices: CatalogItem[] = [
  {
    id: "EST-CF-COMM-001",
    categoryId: "company-formation",
    groupId: "commercial-company",
    title: "تأسيس شركة ذات مسؤولية محدودة",
    displayOrder: 1,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-COMM-002",
    categoryId: "company-formation",
    groupId: "commercial-company",
    title: "تأسيس شركة شخص واحد",
    displayOrder: 2,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-COMM-003",
    categoryId: "company-formation",
    groupId: "commercial-company",
    title: "تأسيس شركة تضامنية",
    displayOrder: 3,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-COMM-004",
    categoryId: "company-formation",
    groupId: "commercial-company",
    title: "تأسيس شركة توصية بسيطة",
    displayOrder: 4,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-COMM-005",
    categoryId: "company-formation",
    groupId: "commercial-company",
    title: "فتح ملف منشأة في وزارة التجارة",
    displayOrder: 5,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-COMM-006",
    categoryId: "company-formation",
    groupId: "commercial-company",
    title: "إصدار رقم سجل تجاري",
    displayOrder: 6,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-COMM-007",
    categoryId: "company-formation",
    groupId: "commercial-company",
    title: "إصدار شهادة انتساب الغرفة التجارية",
    displayOrder: 7,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-IND-001",
    categoryId: "company-formation",
    groupId: "industrial-company",
    title: "تأسيس شركة صناعية",
    displayOrder: 8,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-IND-002",
    categoryId: "company-formation",
    groupId: "industrial-company",
    title: "إصدار ترخيص صناعي",
    displayOrder: 9,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-IND-003",
    categoryId: "company-formation",
    groupId: "industrial-company",
    title: "إصدار سجل تجاري صناعي",
    displayOrder: 10,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-IND-004",
    categoryId: "company-formation",
    groupId: "industrial-company",
    title: "التسجيل في الغرفة التجارية الصناعية",
    displayOrder: 11,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-SERV-001",
    categoryId: "company-formation",
    groupId: "service-company",
    title: "تأسيس شركة مهنية",
    displayOrder: 12,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-SERV-002",
    categoryId: "company-formation",
    groupId: "service-company",
    title: "تأسيس شركة عائلية",
    displayOrder: 13,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-SERV-003",
    categoryId: "company-formation",
    groupId: "service-company",
    title: "إصدار رخصة خدمية",
    displayOrder: 14,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-REAL-001",
    categoryId: "company-formation",
    groupId: "service-company",
    title: "تأسيس شركة عقارية",
    displayOrder: 15,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-REAL-002",
    categoryId: "company-formation",
    groupId: "service-company",
    title: "التسجيل في وزارة الإسكان",
    displayOrder: 16,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-REAL-003",
    categoryId: "company-formation",
    groupId: "service-company",
    title: "الحصول على ترخيص وساطة عقارية",
    displayOrder: 17,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-ENTR-001",
    categoryId: "entrepreneurial-licenses",
    groupId: "entrepreneurial-company",
    title: "تأسيس شركة ريادية",
    displayOrder: 18,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-ENTR-002",
    categoryId: "entrepreneurial-licenses",
    groupId: "entrepreneurial-company",
    title: "تسجيل الشركة الريادية في منشآت",
    displayOrder: 19,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-ENTR-003",
    categoryId: "entrepreneurial-licenses",
    groupId: "entrepreneurial-company",
    title: "إصدار شهادة شركة ريادية",
    displayOrder: 20,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-ENTR-004",
    categoryId: "entrepreneurial-licenses",
    groupId: "entrepreneurial-company",
    title: "ربط الشركة الريادية بالجهات الحكومية",
    displayOrder: 21,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-ENTR-005",
    categoryId: "entrepreneurial-licenses",
    groupId: "entrepreneurial-company",
    title: "إصدار سجل تجاري للشركات الريادية",
    displayOrder: 22,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-ENTR-006",
    categoryId: "entrepreneurial-licenses",
    groupId: "entrepreneurial-company",
    title: "إضافة شركاء في الشركة الريادية",
    displayOrder: 23,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-ENTR-007",
    categoryId: "entrepreneurial-licenses",
    groupId: "entrepreneurial-company",
    title: "تعديل الأنشطة الريادية",
    displayOrder: 24,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-ENTR-008",
    categoryId: "entrepreneurial-licenses",
    groupId: "entrepreneurial-company",
    title: "تحويل الشركة الريادية إلى شركة تجارية",
    displayOrder: 25,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-ENTR-009",
    categoryId: "entrepreneurial-licenses",
    groupId: "entrepreneurial-company",
    title: "صياغة عقد تأسيس لشركة ريادية",
    displayOrder: 26,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-ENTR-010",
    categoryId: "entrepreneurial-licenses",
    groupId: "entrepreneurial-company",
    title: "تحديث بيانات الشركة الريادية",
    displayOrder: 27,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-PR-GENERAL-001",
    categoryId: "premium-residency",
    groupId: "premium-exceptional-competency",
    title: "إقامة مميزة للكفاءة الاستثنائية",
    displayOrder: 97,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-PR-GENERAL-002",
    categoryId: "premium-residency",
    groupId: "premium-talent",
    title: "إقامة مميزة للموهبة",
    displayOrder: 98,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-PR-GENERAL-003",
    categoryId: "premium-residency",
    groupId: "premium-property-owner",
    title: "إقامة مميزة لمالك عقار",
    displayOrder: 99,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-PR-GENERAL-004",
    categoryId: "premium-residency",
    groupId: "premium-entrepreneur",
    title: "إقامة مميزة لرائد أعمال",
    displayOrder: 100,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-PR-GENERAL-005",
    categoryId: "premium-residency",
    groupId: "premium-business-investor",
    title: "إقامة مميزة لمستثمر أعمال",
    displayOrder: 101,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-OTHER-001",
    categoryId: "company-formation",
    groupId: "other-company-types",
    title: "تأسيس شركة نقل ولوجستيات",
    displayOrder: 102,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-PR-GENERAL-006",
    categoryId: "premium-residency",
    groupId: "premium-fixed-term",
    title: "إقامة مميزة محددة المدة",
    displayOrder: 118,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-PR-GENERAL-007",
    categoryId: "premium-residency",
    groupId: "premium-unlimited-term",
    title: "إقامة مميزة غير محددة المدة",
    displayOrder: 119,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-JSC-001",
    categoryId: "company-formation",
    groupId: "joint-stock-company",
    title: "تأسيس شركة مساهمة",
    displayOrder: 124,
    handoffRequired: true,
    handoffMode: "IMMEDIATE",
  },
  {
    id: "EST-ENT-INC-001",
    categoryId: "entrepreneurial-licenses",
    groupId: "entrepreneurial-incubation",
    title: "احتضان مشروع ريادي",
    displayOrder: 125,
    handoffRequired: true,
    handoffMode: "IMMEDIATE",
  },
  {
    id: "EST-LEGAL-COMM-001",
    categoryId: "legal-services",
    groupId: "commercial-cases",
    title: "القضايا التجارية",
    displayOrder: 126,
    handoffRequired: true,
    handoffMode: "IMMEDIATE",
  },
  {
    id: "EST-LEGAL-ADMIN-001",
    categoryId: "legal-services",
    groupId: "administrative-cases",
    title: "القضايا الإدارية",
    displayOrder: 127,
    handoffRequired: true,
    handoffMode: "IMMEDIATE",
  },
  {
    id: "EST-LEGAL-LABOR-001",
    categoryId: "legal-services",
    groupId: "labor-cases",
    title: "القضايا العمالية",
    displayOrder: 128,
    handoffRequired: true,
    handoffMode: "IMMEDIATE",
  },
  {
    id: "EST-LEGAL-ARB-001",
    categoryId: "legal-services",
    groupId: "arbitration-dispute-resolution",
    title: "التحكيم وتسوية المنازعات",
    displayOrder: 129,
    handoffRequired: true,
    handoffMode: "IMMEDIATE",
  },
  {
    id: "EST-LEGAL-CONTRACT-001",
    categoryId: "legal-services",
    groupId: "contracts-agreements",
    title: "صياغة العقود والاتفاقيات",
    displayOrder: 130,
    handoffRequired: true,
    handoffMode: "IMMEDIATE",
  },
  {
    id: "EST-LEGAL-OTHER-001",
    categoryId: "legal-services",
    groupId: "other-legal-cases",
    title: "قضايا أخرى",
    displayOrder: 131,
    handoffRequired: true,
    handoffMode: "IMMEDIATE",
  },
  {
    id: "EST-FIN-CONS-001",
    categoryId: "financial-services",
    groupId: "financial-consultant",
    title: "مستشار مالي",
    displayOrder: 132,
    handoffRequired: true,
    handoffMode: "IMMEDIATE",
  },
  {
    id: "EST-FIN-CPA-001",
    categoryId: "financial-services",
    groupId: "chartered-accountant",
    title: "محاسب قانوني",
    displayOrder: 133,
    handoffRequired: true,
    handoffMode: "IMMEDIATE",
  },
  {
    id: "EST-FIN-DATA-001",
    categoryId: "financial-services",
    groupId: "data-entry-account-review",
    title: "مدخلو بيانات ومراجعو حسابات",
    displayOrder: 134,
    handoffRequired: true,
    handoffMode: "IMMEDIATE",
  },
  {
    id: "EST-FIN-OTHER-001",
    categoryId: "financial-services",
    groupId: "other-financial-services",
    title: "مالية أخرى",
    displayOrder: 135,
    handoffRequired: true,
    handoffMode: "IMMEDIATE",
  },
  {
    id: "EST-MKT-FEAS-001",
    categoryId: "marketing-feasibility",
    groupId: "feasibility-study",
    title: "دراسة جدوى",
    displayOrder: 136,
    handoffRequired: true,
    handoffMode: "IMMEDIATE",
  },
  {
    id: "EST-MKT-BIZDEV-001",
    categoryId: "marketing-feasibility",
    groupId: "marketing-business-development",
    title: "التسويق وتطوير الأعمال",
    displayOrder: 137,
    handoffRequired: true,
    handoffMode: "IMMEDIATE",
  },
  {
    id: "EST-GOV-MGMT-001",
    categoryId: "government-procedures",
    groupId: "government-platform-management",
    title: "إدارة المنصات الحكومية",
    displayOrder: 138,
    handoffRequired: true,
    handoffMode: "IMMEDIATE",
  },
  {
    id: "EST-GOV-VISIT-001",
    categoryId: "government-procedures",
    groupId: "government-entity-visit",
    title: "إنجاز إجراء بزيارة جهة حكومية",
    displayOrder: 139,
    handoffRequired: true,
    handoffMode: "IMMEDIATE",
  },
  {
    id: "EST-WORK-PRIVATE-001",
    categoryId: "ready-workspaces",
    groupId: "private-office",
    title: "مكتب مغلق",
    displayOrder: 140,
    handoffRequired: true,
    handoffMode: "IMMEDIATE",
  },
  {
    id: "EST-WORK-SHARED-001",
    categoryId: "ready-workspaces",
    groupId: "shared-office",
    title: "مكتب مشترك",
    displayOrder: 141,
    handoffRequired: true,
    handoffMode: "IMMEDIATE",
  },
]
