export interface CatalogCategory {
  id: string
  title: string
  icon: string
  subtitle: string
  displayOrder: number
}

export interface CatalogGroup {
  id: string
  categoryId: string
  title: string
  icon: string
  displayOrder: number
}

export interface CatalogItem {
  id: string
  categoryId: string
  groupId: string
  title: string
  displayOrder: number
  handoffRequired: boolean
  handoffMode: string
}

// Generated from the approved Phase 2 Master Catalog.
// Included rows: active=true, review_status=APPROVED, lifecycle_status=ACTIVE.
// Source workbook remains the governance source of truth.

export const catalogCategories: CatalogCategory[] = [
  {
    id: "company-formation",
    title: "تأسيس شركات",
    icon: "🏢",
    subtitle: "ابدأ شركتك بخطوات واضحة ومنظمة",
    displayOrder: 1,
  },
  {
    id: "government-services",
    title: "الخدمات الحكومية",
    icon: "🏛️",
    subtitle: "قوى • بلدي • مقيم • ZATCA والمزيد",
    displayOrder: 2,
  },
  {
    id: "premium-residency",
    title: "الإقامة المميزة",
    icon: "⭐",
    subtitle: "استعرض الخيارات وحدد المسار المناسب",
    displayOrder: 3,
  },
]

export const catalogGroups: CatalogGroup[] = [
  {
    id: "commercial-company",
    categoryId: "company-formation",
    title: "تأسيس شركة تجارية",
    icon: "🏢",
    displayOrder: 1,
  },
  {
    id: "industrial-company",
    categoryId: "company-formation",
    title: "تأسيس شركة صناعية",
    icon: "🏭",
    displayOrder: 2,
  },
  {
    id: "service-company",
    categoryId: "company-formation",
    title: "تأسيس شركة خدمية",
    icon: "🧩",
    displayOrder: 3,
  },
  {
    id: "real-estate-company",
    categoryId: "company-formation",
    title: "تأسيس شركة عقارية",
    icon: "🏗️",
    displayOrder: 4,
  },
  {
    id: "entrepreneurial-company",
    categoryId: "company-formation",
    title: "تأسيس شركة ريادية",
    icon: "🚀",
    displayOrder: 5,
  },
  {
    id: "qiwa",
    categoryId: "government-services",
    title: "منصة قوى",
    icon: "🏢",
    displayOrder: 1,
  },
  {
    id: "commerce",
    categoryId: "government-services",
    title: "وزارة التجارة (المركز السعودي للأعمال)",
    icon: "🏛️",
    displayOrder: 2,
  },
  {
    id: "balady",
    categoryId: "government-services",
    title: "منصة بلدي",
    icon: "🏙️",
    displayOrder: 3,
  },
  {
    id: "muqeem",
    categoryId: "government-services",
    title: "منصة مقيم",
    icon: "🪪",
    displayOrder: 4,
  },
  {
    id: "zatca",
    categoryId: "government-services",
    title: "منصة الزكاة والضريبة والجمارك (ZATCA)",
    icon: "🧾",
    displayOrder: 5,
  },
  {
    id: "mudad",
    categoryId: "government-services",
    title: "منصة مدد حماية الأجور",
    icon: "📋",
    displayOrder: 6,
  },
  {
    id: "national-address",
    categoryId: "government-services",
    title: "العنوان الوطني",
    icon: "📍",
    displayOrder: 7,
  },
  {
    id: "chamber",
    categoryId: "government-services",
    title: "الغرفة التجارية",
    icon: "🏛️",
    displayOrder: 8,
  },
  {
    id: "premium-residency-options",
    categoryId: "premium-residency",
    title: "خيارات الإقامة المميزة",
    icon: "⭐",
    displayOrder: 1,
  },
  {
    id: "other-company-types",
    categoryId: "company-formation",
    title: "أنواع أخرى",
    icon: "📁",
    displayOrder: 6,
  },
  {
    id: "insurance",
    categoryId: "government-services",
    title: "التأمين",
    icon: "🛡️",
    displayOrder: 9,
  },
]

export const catalogServices: CatalogItem[] = [
  {
    id: "EST-CF-COMM-001",
    categoryId: "company-formation",
    groupId: "commercial-company",
    title: "تأسيس شركة ذات مسؤولية محدودة",
    displayOrder: 1,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-COMM-002",
    categoryId: "company-formation",
    groupId: "commercial-company",
    title: "تأسيس شركة شخص واحد",
    displayOrder: 2,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-COMM-003",
    categoryId: "company-formation",
    groupId: "commercial-company",
    title: "تأسيس شركة تضامنية",
    displayOrder: 3,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-COMM-004",
    categoryId: "company-formation",
    groupId: "commercial-company",
    title: "تأسيس شركة توصية بسيطة",
    displayOrder: 4,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-COMM-005",
    categoryId: "company-formation",
    groupId: "commercial-company",
    title: "فتح ملف منشأة في وزارة التجارة",
    displayOrder: 5,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-COMM-006",
    categoryId: "company-formation",
    groupId: "commercial-company",
    title: "إصدار رقم سجل تجاري",
    displayOrder: 6,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-COMM-007",
    categoryId: "company-formation",
    groupId: "commercial-company",
    title: "إصدار شهادة انتساب الغرفة التجارية",
    displayOrder: 7,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-IND-001",
    categoryId: "company-formation",
    groupId: "industrial-company",
    title: "تأسيس شركة صناعية",
    displayOrder: 8,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-IND-002",
    categoryId: "company-formation",
    groupId: "industrial-company",
    title: "إصدار ترخيص صناعي",
    displayOrder: 9,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-IND-003",
    categoryId: "company-formation",
    groupId: "industrial-company",
    title: "إصدار سجل تجاري صناعي",
    displayOrder: 10,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-IND-004",
    categoryId: "company-formation",
    groupId: "industrial-company",
    title: "التسجيل في الغرفة التجارية الصناعية",
    displayOrder: 11,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-SERV-001",
    categoryId: "company-formation",
    groupId: "service-company",
    title: "تأسيس شركة مهنية",
    displayOrder: 12,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-SERV-002",
    categoryId: "company-formation",
    groupId: "service-company",
    title: "تأسيس شركة عائلية",
    displayOrder: 13,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-SERV-003",
    categoryId: "company-formation",
    groupId: "service-company",
    title: "إصدار رخصة خدمية",
    displayOrder: 14,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-REAL-001",
    categoryId: "company-formation",
    groupId: "real-estate-company",
    title: "تأسيس شركة عقارية",
    displayOrder: 15,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-REAL-002",
    categoryId: "company-formation",
    groupId: "real-estate-company",
    title: "التسجيل في وزارة الإسكان",
    displayOrder: 16,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-REAL-003",
    categoryId: "company-formation",
    groupId: "real-estate-company",
    title: "الحصول على ترخيص وساطة عقارية",
    displayOrder: 17,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-ENTR-001",
    categoryId: "company-formation",
    groupId: "entrepreneurial-company",
    title: "تأسيس شركة ريادية",
    displayOrder: 18,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-ENTR-002",
    categoryId: "company-formation",
    groupId: "entrepreneurial-company",
    title: "تسجيل الشركة الريادية في منشآت",
    displayOrder: 19,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-ENTR-003",
    categoryId: "company-formation",
    groupId: "entrepreneurial-company",
    title: "إصدار شهادة شركة ريادية",
    displayOrder: 20,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-ENTR-004",
    categoryId: "company-formation",
    groupId: "entrepreneurial-company",
    title: "ربط الشركة الريادية بالجهات الحكومية",
    displayOrder: 21,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-ENTR-005",
    categoryId: "company-formation",
    groupId: "entrepreneurial-company",
    title: "إصدار سجل تجاري للشركات الريادية",
    displayOrder: 22,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-ENTR-006",
    categoryId: "company-formation",
    groupId: "entrepreneurial-company",
    title: "إضافة شركاء في الشركة الريادية",
    displayOrder: 23,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-ENTR-007",
    categoryId: "company-formation",
    groupId: "entrepreneurial-company",
    title: "تعديل الأنشطة الريادية",
    displayOrder: 24,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-ENTR-008",
    categoryId: "company-formation",
    groupId: "entrepreneurial-company",
    title: "تحويل الشركة الريادية إلى شركة تجارية",
    displayOrder: 25,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-ENTR-009",
    categoryId: "company-formation",
    groupId: "entrepreneurial-company",
    title: "صياغة عقد تأسيس لشركة ريادية",
    displayOrder: 26,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-ENTR-010",
    categoryId: "company-formation",
    groupId: "entrepreneurial-company",
    title: "تحديث بيانات الشركة الريادية",
    displayOrder: 27,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-QIWA-001",
    categoryId: "government-services",
    groupId: "qiwa",
    title: "تسجيل موظف جديد",
    displayOrder: 28,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-QIWA-005",
    categoryId: "government-services",
    groupId: "qiwa",
    title: "إزالة الموظفين من المنشأة",
    displayOrder: 32,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-QIWA-006",
    categoryId: "government-services",
    groupId: "qiwa",
    title: "إدارة مشرفي المنشأة",
    displayOrder: 33,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-QIWA-007",
    categoryId: "government-services",
    groupId: "qiwa",
    title: "رفع ملفات الأجور",
    displayOrder: 34,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-QIWA-009",
    categoryId: "government-services",
    groupId: "qiwa",
    title: "تحديث بيانات منشأة",
    displayOrder: 36,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-MOC-001",
    categoryId: "government-services",
    groupId: "commerce",
    title: "إصدار رخصة تجارية",
    displayOrder: 37,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-MOC-002",
    categoryId: "government-services",
    groupId: "commerce",
    title: "قيد سجل تجاري",
    displayOrder: 38,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-MOC-003",
    categoryId: "government-services",
    groupId: "commerce",
    title: "تجديد السجل التجاري",
    displayOrder: 39,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-MOC-004",
    categoryId: "government-services",
    groupId: "commerce",
    title: "تعديل السجل التجاري",
    displayOrder: 40,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-MOC-005",
    categoryId: "government-services",
    groupId: "commerce",
    title: "شطب سجل تجاري",
    displayOrder: 41,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-MOC-006",
    categoryId: "government-services",
    groupId: "commerce",
    title: "إضافة أو إزالة شركاء",
    displayOrder: 42,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-MOC-007",
    categoryId: "government-services",
    groupId: "commerce",
    title: "تحويل كيان الشركة",
    displayOrder: 43,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-MOC-008",
    categoryId: "government-services",
    groupId: "commerce",
    title: "تعديل عقد التأسيس / النظام الأساس",
    displayOrder: 44,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-MOC-009",
    categoryId: "government-services",
    groupId: "commerce",
    title: "إصدار مستخرج السجل التجاري",
    displayOrder: 45,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-BALADY-001",
    categoryId: "government-services",
    groupId: "balady",
    title: "إصدار رخصة تجارية",
    displayOrder: 46,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-BALADY-003",
    categoryId: "government-services",
    groupId: "balady",
    title: "تعديل رخصة تجارية",
    displayOrder: 48,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-BALADY-004",
    categoryId: "government-services",
    groupId: "balady",
    title: "إلغاء رخصة تجارية",
    displayOrder: 49,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-BALADY-005",
    categoryId: "government-services",
    groupId: "balady",
    title: "إصدار لوحة",
    displayOrder: 50,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-BALADY-006",
    categoryId: "government-services",
    groupId: "balady",
    title: "طباعة لوحة",
    displayOrder: 51,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-BALADY-007",
    categoryId: "government-services",
    groupId: "balady",
    title: "إضافة أنشطة",
    displayOrder: 52,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-BALADY-008",
    categoryId: "government-services",
    groupId: "balady",
    title: "إزالة أنشطة",
    displayOrder: 53,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-BALADY-009",
    categoryId: "government-services",
    groupId: "balady",
    title: "رفع الارتدادات",
    displayOrder: 54,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-BALADY-010",
    categoryId: "government-services",
    groupId: "balady",
    title: "إصدار شهادات صحية",
    displayOrder: 55,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-MUQEEM-001",
    categoryId: "government-services",
    groupId: "muqeem",
    title: "إصدار إقامة",
    displayOrder: 56,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-MUQEEM-002",
    categoryId: "government-services",
    groupId: "muqeem",
    title: "تجديد إقامة",
    displayOrder: 57,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-MUQEEM-003",
    categoryId: "government-services",
    groupId: "muqeem",
    title: "تعديل مهنة",
    displayOrder: 58,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-MUQEEM-004",
    categoryId: "government-services",
    groupId: "muqeem",
    title: "طباعة إقامة",
    displayOrder: 59,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-MUQEEM-005",
    categoryId: "government-services",
    groupId: "muqeem",
    title: "إصدار تأشيرة خروج وعودة",
    displayOrder: 60,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-MUQEEM-006",
    categoryId: "government-services",
    groupId: "muqeem",
    title: "إصدار تأشيرة خروج نهائي",
    displayOrder: 61,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-MUQEEM-007",
    categoryId: "government-services",
    groupId: "muqeem",
    title: "نقل خدمات أو رفع ملف إقامة",
    displayOrder: 62,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-MUQEEM-008",
    categoryId: "government-services",
    groupId: "muqeem",
    title: "إسقاط عامل خرج ولم يعد",
    displayOrder: 63,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-MUQEEM-009",
    categoryId: "government-services",
    groupId: "muqeem",
    title: "تحديث معلومات الجواز",
    displayOrder: 64,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-MUQEEM-010",
    categoryId: "government-services",
    groupId: "muqeem",
    title: "إصدار تقرير مقيم",
    displayOrder: 65,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-MUQEEM-011",
    categoryId: "government-services",
    groupId: "muqeem",
    title: "تجديد اشتراك أبشر أعمال",
    displayOrder: 66,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-ZATCA-001",
    categoryId: "government-services",
    groupId: "zatca",
    title: "تسجيل أو فتح ملف شركة بالزكاة",
    displayOrder: 67,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-ZATCA-003",
    categoryId: "government-services",
    groupId: "zatca",
    title: "إصدار شهادة تسجيل ضريبي",
    displayOrder: 69,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-ZATCA-005",
    categoryId: "government-services",
    groupId: "zatca",
    title: "تعديل بيانات ضريبية",
    displayOrder: 71,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-ZATCA-006",
    categoryId: "government-services",
    groupId: "zatca",
    title: "تقديم إقرار ضريبي",
    displayOrder: 72,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-ZATCA-007",
    categoryId: "government-services",
    groupId: "zatca",
    title: "إلغاء الرقم المميز",
    displayOrder: 73,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-ZATCA-008",
    categoryId: "government-services",
    groupId: "zatca",
    title: "ربط تحديث الرقم الضريبي",
    displayOrder: 74,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-ZATCA-010",
    categoryId: "government-services",
    groupId: "zatca",
    title: "ربط الفوترة الإلكترونية ERP",
    displayOrder: 76,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-ZATCA-011",
    categoryId: "government-services",
    groupId: "zatca",
    title: "رفع الفواتير الإلكترونية",
    displayOrder: 77,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-ZATCA-012",
    categoryId: "government-services",
    groupId: "zatca",
    title: "حل مخالفات الفوترة الإلكترونية",
    displayOrder: 78,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-ZATCA-013",
    categoryId: "government-services",
    groupId: "zatca",
    title: "حل مخالفات المتطلبات الضريبية",
    displayOrder: 79,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-ZATCA-014",
    categoryId: "government-services",
    groupId: "zatca",
    title: "شهادة خلو طرف",
    displayOrder: 80,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-ZATCA-015",
    categoryId: "government-services",
    groupId: "zatca",
    title: "طباعة الشهادات الضريبية",
    displayOrder: 81,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-MUDAD-001",
    categoryId: "government-services",
    groupId: "mudad",
    title: "التسجيل في منصة مدد",
    displayOrder: 82,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-MUDAD-002",
    categoryId: "government-services",
    groupId: "mudad",
    title: "رفع ملف حماية الأجور",
    displayOrder: 83,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-MUDAD-003",
    categoryId: "government-services",
    groupId: "mudad",
    title: "رفع الرواتب شهريًا",
    displayOrder: 84,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-MUDAD-004",
    categoryId: "government-services",
    groupId: "mudad",
    title: "مطابقة ملف فئة رواتب أو شهر",
    displayOrder: 85,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-MUDAD-005",
    categoryId: "government-services",
    groupId: "mudad",
    title: "تصحيح بيانات في مدد أو حماية أجور",
    displayOrder: 86,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-NADDR-001",
    categoryId: "government-services",
    groupId: "national-address",
    title: "تسجيل العنوان الوطني للأعمال",
    displayOrder: 87,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-NADDR-002",
    categoryId: "government-services",
    groupId: "national-address",
    title: "تحديث بيانات العنوان الوطني",
    displayOrder: 88,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-NADDR-003",
    categoryId: "government-services",
    groupId: "national-address",
    title: "العنوان المختصر",
    displayOrder: 89,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-NADDR-004",
    categoryId: "government-services",
    groupId: "national-address",
    title: "ربط العنوان عبر عدة منصات",
    displayOrder: 90,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-NADDR-005",
    categoryId: "government-services",
    groupId: "national-address",
    title: "طلب إثبات عنوان وطني",
    displayOrder: 91,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-COC-002",
    categoryId: "government-services",
    groupId: "chamber",
    title: "تصديق عقود أو أوراق",
    displayOrder: 93,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-COC-003",
    categoryId: "government-services",
    groupId: "chamber",
    title: "إضافة أو إزالة مفوض",
    displayOrder: 94,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-COC-005",
    categoryId: "government-services",
    groupId: "chamber",
    title: "تحديث بيانات أو نقل عضوية",
    displayOrder: 96,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-PR-GENERAL-001",
    categoryId: "premium-residency",
    groupId: "premium-residency-options",
    title: "إقامة الكفاءة الاستثنائية",
    displayOrder: 97,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-PR-GENERAL-002",
    categoryId: "premium-residency",
    groupId: "premium-residency-options",
    title: "إقامة الموهبة",
    displayOrder: 98,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-PR-GENERAL-003",
    categoryId: "premium-residency",
    groupId: "premium-residency-options",
    title: "إقامة مالك عقار",
    displayOrder: 99,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-PR-GENERAL-004",
    categoryId: "premium-residency",
    groupId: "premium-residency-options",
    title: "إقامة رائد أعمال",
    displayOrder: 100,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-PR-GENERAL-005",
    categoryId: "premium-residency",
    groupId: "premium-residency-options",
    title: "إقامة مستثمر أعمال",
    displayOrder: 101,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-CF-OTHER-001",
    categoryId: "company-formation",
    groupId: "other-company-types",
    title: "تأسيس شركة نقل ولوجستيات",
    displayOrder: 102,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-QIWA-010",
    categoryId: "government-services",
    groupId: "qiwa",
    title: "إضافة مدير حساب الفروع",
    displayOrder: 103,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-QIWA-011",
    categoryId: "government-services",
    groupId: "qiwa",
    title: "استكمال بيانات الموظفين",
    displayOrder: 104,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-QIWA-012",
    categoryId: "government-services",
    groupId: "qiwa",
    title: "إدارة مالك المنشأة",
    displayOrder: 105,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-QIWA-013",
    categoryId: "government-services",
    groupId: "qiwa",
    title: "إصدار شهادة التزام التأمينات",
    displayOrder: 106,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-MOC-010",
    categoryId: "government-services",
    groupId: "commerce",
    title: "مواءمة الشركات",
    displayOrder: 107,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-MUQEEM-012",
    categoryId: "government-services",
    groupId: "muqeem",
    title: "توصيل الوثائق",
    displayOrder: 108,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-ZATCA-016",
    categoryId: "government-services",
    groupId: "zatca",
    title: "التسجيل في ضريبة القيمة المضافة",
    displayOrder: 109,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-ZATCA-017",
    categoryId: "government-services",
    groupId: "zatca",
    title: "تقديم إقرار زكوي تقديري",
    displayOrder: 110,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-ZATCA-018",
    categoryId: "government-services",
    groupId: "zatca",
    title: "إصدار شهادة الزكاة",
    displayOrder: 111,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-MUDAD-006",
    categoryId: "government-services",
    groupId: "mudad",
    title: "تحديث بيانات الموظفين",
    displayOrder: 112,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-COC-006",
    categoryId: "government-services",
    groupId: "chamber",
    title: "تصديق التأشيرات",
    displayOrder: 113,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-COC-007",
    categoryId: "government-services",
    groupId: "chamber",
    title: "إصدار شهادة إعادة تصدير",
    displayOrder: 114,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-COC-008",
    categoryId: "government-services",
    groupId: "chamber",
    title: "تقديم تصريح لإقامة مسابقة",
    displayOrder: 115,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-INSURANCE-001",
    categoryId: "government-services",
    groupId: "insurance",
    title: "التأمين الطبي للموظفين والعمال",
    displayOrder: 116,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-INSURANCE-002",
    categoryId: "government-services",
    groupId: "insurance",
    title: "تأمين الشركات",
    displayOrder: 117,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-PR-GENERAL-006",
    categoryId: "premium-residency",
    groupId: "premium-residency-options",
    title: "إقامة محددة المدة",
    displayOrder: 118,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-PR-GENERAL-007",
    categoryId: "premium-residency",
    groupId: "premium-residency-options",
    title: "إقامة غير محددة المدة",
    displayOrder: 119,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-QIWA-014",
    categoryId: "government-services",
    groupId: "qiwa",
    title: "رفع عقد عمل",
    displayOrder: 120,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-QIWA-015",
    categoryId: "government-services",
    groupId: "qiwa",
    title: "تعديل عقد عمل",
    displayOrder: 121,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-QIWA-016",
    categoryId: "government-services",
    groupId: "qiwa",
    title: "إلغاء عقد عمل",
    displayOrder: 122,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
  {
    id: "EST-GS-QIWA-017",
    categoryId: "government-services",
    groupId: "qiwa",
    title: "تعديل حالة عقد عمل",
    displayOrder: 123,
    handoffRequired: true,
    handoffMode: "CONDITIONAL",
  },
]
